/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 scene.gltf -T --shadows
Author: Akshat (https://sketchfab.com/shooter24994)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/saturn-8fb67d3defd74aaa880df3a08317e641
Title: Saturn
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Saturn(props) {
  const { nodes, materials } = useGLTF('/models/saturn-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Sphere_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh castShadow receiveShadow geometry={nodes.Circle_ring_0.geometry} material={materials.ring} rotation={[-Math.PI / 2, 0.24, 0]} scale={163.36} />
    </group>
  )
}

useGLTF.preload('/models/saturn-transformed.glb')
