/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 scene.gltf -T --shadows
Author: uperesito (https://sketchfab.com/uperesito)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pluton-v11-b455b83fd25f46309a3d8711033e08a1
Title: Pluton v1.1
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pluto(props) {
  const { nodes, materials } = useGLTF('/models/pluto-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 2.42]} />
    </group>
  )
}

useGLTF.preload('/models/pluto-transformed.glb')
