/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 scene.gltf -T --shadows
Author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/daphne-planetoid-d7dd7ff088b04813ae26798a67d11c58
Title: Daphne planetoid
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Daphne(props) {
  const { nodes, materials } = useGLTF('/models/daphne-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Daphe_LP_Debris_2_0.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Daphne_LP_1_0.geometry} material={materials.material_1} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/daphne-transformed.glb')
