/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 scene.gltf -T --shadows
Author: Akshat (https://sketchfab.com/shooter24994)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/uranus-4d2f0c3674904472ac413fdabbf491d7
Title: Uranus
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Uranus(props) {
  const { nodes, materials } = useGLTF('/models/uranus-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, Math.PI]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.Sphere_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.Circle_ring_0.geometry} material={materials.ring} rotation={[-Math.PI / 2, 1.37, 0]} scale={154.21} />
          <mesh castShadow receiveShadow geometry={nodes.Circle001_ring_0.geometry} material={materials.ring} rotation={[-Math.PI / 2, 1.37, 0]} scale={147.68} />
          <mesh castShadow receiveShadow geometry={nodes.Circle002_ring_0.geometry} material={materials.ring} rotation={[-Math.PI / 2, 1.37, 0]} scale={140.92} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/uranus-transformed.glb')
