/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 scene.gltf -T --shadows
Author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toutatis-asteroid-potential-earths-impactor-5446cb4764674e49a5e4eda95ed497dc
Title: Toutatis asteroid - potential Earth`s impactor
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Toutatis(props) {
  const { nodes, materials } = useGLTF('/models/toutatis-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Toutatis_LP_default_0.geometry} material={materials['default']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/toutatis-transformed.glb')
